# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_edit_data_barang.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from database.connect import get_connection
from models.produk import Produk
from models.produk import AksesorisHewan, MakananHewan
from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)

        # ================== LABEL TITLE ==================
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 30, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setText("Update Data Produk")

        # ================== LABELS ==================
        labels = ["ID", "Nama", "Stok", "Harga", "Jenis Hewan", "Kategori"]
        positions = [120, 170, 220, 260, 310, 360]
        self.label_objects = []

        for text, y in zip(labels, positions):
                lbl = QtWidgets.QLabel(self.centralwidget)
                lbl.setGeometry(QtCore.QRect(160, y, 100, 31))
                f = QtGui.QFont()
                f.setPointSize(11)
                lbl.setFont(f)
                lbl.setText(text)
                self.label_objects.append(lbl)

        # ================== INPUT FIELD ==================
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)       # ID
        self.lineEdit.setGeometry(QtCore.QRect(280, 110, 241, 41))

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)     # Nama
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 160, 311, 41))

        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)     # Stok
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 210, 311, 41))

        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)     # Harga
        self.lineEdit_4.setGeometry(QtCore.QRect(280, 260, 311, 41))

        # =============== JENIS HEWAN (TEXT INPUT, BUKAN COMBOBOX) ===============
        self.lineEdit_jenis = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jenis.setGeometry(QtCore.QRect(280, 310, 311, 41))

        # =============== KATEGORI (COMBOBOX) ===============
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(280, 360, 311, 41))
        self.comboBox_3.addItems(["Makanan Hewan", "Aksesoris Hewan"])

        # ================== BUTTON CARI ==================
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 110, 71, 41))
        self.pushButton_2.setText("Cari")

        # ================== BUTTON UPDATE ==================
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 440, 181, 51))
        self.pushButton.setText("Update")

        # ================== BUTTON BACK ==================
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 440, 181, 51))
        self.pushButton_3.setText("Back")

        # EVENT
        self.pushButton_2.clicked.connect(self.searchData)
        self.pushButton.clicked.connect(self.updateData)
        self.pushButton_3.clicked.connect(self.goBack)

                # ================== CSS STYLE ==================
        style = """
        QLabel {
            color: #333333;
        }

        QLineEdit, QComboBox {
            background-color: #FFFFFF;
            color: #333333;
            border: 2px solid #555555;
            border-radius: 6px;
            padding: 4px;
        }

        QLineEdit:focus, QComboBox:focus {
            border: 2px solid #222222;
        }

        QPushButton {
            background-color: #555555;
            color: white;
            border-radius: 8px;
            padding: 6px 12px;
        }

        QPushButton:hover {
            background-color: #666666;
        }

        QPushButton:pressed {
            background-color: #777777;
        }
        """

        self.centralwidget.setStyleSheet(style)


        MainWindow.setCentralWidget(self.centralwidget)

    # ================== SEARCH ==================
    def searchData(self):
        try:
            id_produk = self.lineEdit.text()

            db, cursor = get_connection()
            cursor.execute("SELECT * FROM produk WHERE id_produk=%s", (id_produk,))
            data = cursor.fetchone()

            if not data:
                QMessageBox.warning(self.centralwidget, "Error", "ID tidak ditemukan!")
                return

            # SET FIELD
            self.lineEdit_2.setText(data[1])
            self.lineEdit_3.setText(str(data[3]))
            self.lineEdit_4.setText(str(data[2]))

            # JENIS HEWAN (pakai lineEdit biasa)
            self.lineEdit_jenis.setText(data[4])

            # KATEGORI
            index2 = self.comboBox_3.findText(data[5])
            if index2 >= 0:
                self.comboBox_3.setCurrentIndex(index2)

        except Exception as e:
            print("SEARCH ERROR:", e)

    # ================== UPDATE ==================
    def updateData(self):
        try:
            id_produk = self.lineEdit.text()
            nama = self.lineEdit_2.text()
            stok = self.lineEdit_3.text()
            harga = self.lineEdit_4.text()
            jenis_hewan = self.lineEdit_jenis.text()  # <-- FIX
            kategori = self.comboBox_3.currentText()

            db, cursor = get_connection()

            cursor.execute("""
                UPDATE produk SET 
                nama_produk=%s, harga=%s, stok=%s, jenis_hewan=%s, kategori=%s
                WHERE id_produk=%s
            """, (nama, harga, stok, jenis_hewan, kategori, id_produk))
            db.commit()

            QMessageBox.information(self.centralwidget, "Sukses", "Data berhasil diupdate!")

        except Exception as e:
            print("UPDATE ERROR:", e)

    # ================== BACK ==================
    def goBack(self):
        self.MainWindow.close()

        # kembali ke dashboard supervisor
        from dashboard.dashboard_supervisor import Ui_MainWindow as DashboardSupervisor
        from PyQt5 import QtWidgets

        self.sup = QtWidgets.QMainWindow()
        self.ui_sup = DashboardSupervisor()
        self.ui_sup.setupUi(self.sup)
        self.sup.show()


# ================== MAIN ==================
if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
