# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_supervisor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import ui.form_login as login
import ui.supervisor.form_insert_data_barang as tb
import ui.supervisor.form_edit_data_barang as eb
import ui.supervisor.form_delete_data_barang as db
import ui.supervisor.form_lihat_data_barang as lb
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.main_window = MainWindow 
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 20, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 150, 241, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #66d9a3,\n"
"    stop:1 #33cc88\n"
");\n"
"color: white;\n"
"border-radius: 8px;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 320, 241, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ff9aa2,   /* soft pink-ish red */\n"
"        stop:1 #ff6f6f    /* soft coral red */\n"
"    );\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 6px 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ff8c99,\n"
"        stop:1 #ff5f5f\n"
"    );\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #e85c5c;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(430, 320, 241, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #d9d9d9,\n"
"    stop:1 #bfbfbf\n"
");\n"
"color: black;\n"
"border-radius: 8px;\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(430, 150, 241, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #4da6ff,\n"
"    stop:1 #1a75ff\n"
");\n"
"color: white;\n"
"border-radius: 8px;\n"
"padding: 6px 14px;\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_logout = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_logout.setGeometry(QtCore.QRect(660, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_logout.setFont(font)
        self.pushButton_logout.setStyleSheet("QPushButton {\n"
"    background-color: #4A4A4A;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 6px 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3A3A3A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2E2E2E;\n"
"}\n"
"")
        self.pushButton_logout.setObjectName("pushButton_logout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # --- FIX DESIGN TEXT VISIBILITY & FONT SIZE ---
        self.label.setStyleSheet("color: black; font-size: 24px; font-weight: bold;")
        # Memastikan semua tombol menampilkan teks dengan ukuran jelas
        for btn in [self.pushButton, self.pushButton_2, self.pushButton_4, self.pushButton_logout]:
                btn.setStyleSheet(btn.styleSheet() + "\nfont-size: 16px;\ncolor: black;")


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dashboard Supervisor"))

        self.label.setText(_translate("MainWindow", "DASHBOARD SUPERVISOR"))

        self.pushButton.setText(_translate("MainWindow", "INSERT DATA PRODUK"))
        self.pushButton_2.setText(_translate("MainWindow", "DELETE DATA PRODUK"))
        self.pushButton_3.setText(_translate("MainWindow", "LIHAT DATA PRODUK"))
        self.pushButton_4.setText(_translate("MainWindow", "UPDATE DATA PRODUK"))
        self.pushButton_logout.setText(_translate("MainWindow", "LOGOUT"))

        # Pastikan font tombol seperti dashboard admin
        for btn in [self.pushButton, self.pushButton_2, self.pushButton_3, self.pushButton_4]:
                btn.setStyleSheet(btn.styleSheet() + """
                font-size: 14px;
                font-weight: bold;
                text-transform: uppercase;
                color: white;
                """)

        self.pushButton_3.setStyleSheet(self.pushButton_3.styleSheet() + "color: black;")  # abu = tulisan hitam

        # ---- EVENT KLIK ----
        self.pushButton.clicked.connect(self.openTambahProduk)
        self.pushButton_2.clicked.connect(self.openDeleteProduk)
        self.pushButton_3.clicked.connect(self.openLihatProduk)
        self.pushButton_4.clicked.connect(self.openEditProduk)
        self.pushButton_logout.clicked.connect(self.logout)


                
    def openTambahProduk(self):
        self.window = QtWidgets.QMainWindow()
        self.ui_other = tb.Ui_MainWindow()
        self.ui_other.setupUi(self.window)
        self.ui_other.dashboard = self
        self.window.show()
        self.centralwidget.window().hide()

    def openEditProduk(self):
        self.window = QtWidgets.QMainWindow()
        self.ui_other = eb.Ui_MainWindow()
        self.ui_other.setupUi(self.window)
        self.ui_other.dashboard = self
        self.window.show()
        self.centralwidget.window().hide()

    def openDeleteProduk(self):
        self.window = QtWidgets.QMainWindow()
        self.ui_other = db.Ui_MainWindow()
        self.ui_other.setupUi(self.window)
        self.ui_other.dashboard = self
        self.window.show()
        self.centralwidget.window().hide()

    def openLihatProduk(self):
        self.window = QtWidgets.QMainWindow()
        self.ui_other = lb.Ui_MainWindow()
        self.ui_other.setupUi(self.window)
        self.ui_other.dashboard = self
        self.window.show()
        self.centralwidget.window().hide()

    def logout(self):
        self.window = QtWidgets.QMainWindow()
        self.login = login.Ui_MainWindow()
        self.login.setupUi(self.window)
        self.window.show()
        self.centralwidget.window().hide()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
