# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_data_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from models.User import Admin
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                self.main_window = MainWindow
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(800, 600)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(250, 30, 311, 51))
                font = QtGui.QFont()
                font.setPointSize(18)
                font.setBold(True)
                font.setWeight(75)
                self.label.setFont(font)
                self.label.setObjectName("label")
                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(150, 300, 81, 21))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.label_3.setFont(font)
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(150, 160, 81, 31))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.label_4.setFont(font)
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(180, 240, 55, 16))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.label_5.setFont(font)
                self.label_5.setObjectName("label_5")
                self.label_6 = QtWidgets.QLabel(self.centralwidget)
                self.label_6.setGeometry(QtCore.QRect(180, 370, 55, 16))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.label_6.setFont(font)
                self.label_6.setObjectName("label_6")
                self.pushButton = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton.setGeometry(QtCore.QRect(530, 160, 71, 41))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.pushButton.setFont(font)
                self.pushButton.setStyleSheet("QPushButton {\n"
        "    background-color: #555555;\n"
        "    color: white;\n"
        "    border-radius: 8px;\n"
        "    padding: 6px 12px;\n"
        "}\n"
        "\n"
        "QPushButton:hover {\n"
        "    background-color: #666666;\n"
        "}\n"
        "\n"
        "QPushButton:pressed {\n"
        "    background-color: #777777;\n"
        "}")
                self.pushButton.setObjectName("pushButton")
                self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_2.setGeometry(QtCore.QRect(170, 420, 191, 51))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.pushButton_2.setFont(font)
                self.pushButton_2.setStyleSheet("QPushButton {\n"
        "    background-color: #555555;\n"
        "    color: white;\n"
        "    border-radius: 8px;\n"
        "    padding: 6px 12px;\n"
        "}\n"
        "\n"
        "QPushButton:hover {\n"
        "    background-color: #666666;\n"
        "}\n"
        "\n"
        "QPushButton:pressed {\n"
        "    background-color: #777777;\n"
        "}")
                self.pushButton_2.setObjectName("pushButton_2")
                self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEdit_2.setGeometry(QtCore.QRect(270, 160, 251, 41))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.lineEdit_2.setFont(font)
                self.lineEdit_2.setStyleSheet("QLineEdit {\n"
        "    background-color: #FFFFFF;\n"
        "    color: #000000;\n"
        "    border: 2px solid #888888;\n"
        "    border-radius: 6px;\n"
        "    padding: 4px;\n"
        "}\n"
        "\n"
        "QLineEdit:focus {\n"
        "    border: 2px solid #AAAAAA;\n"
        "}")
                self.lineEdit_2.setObjectName("lineEdit_2")
                self.label_7 = QtWidgets.QLabel(self.centralwidget)
                self.label_7.setGeometry(QtCore.QRect(270, 240, 331, 41))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_7.setFont(font)
                self.label_7.setText("")
                self.label_7.setObjectName("label_7")
                self.label_8 = QtWidgets.QLabel(self.centralwidget)
                self.label_8.setGeometry(QtCore.QRect(270, 300, 331, 41))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_8.setFont(font)
                self.label_8.setText("")
                self.label_8.setObjectName("label_8")
                self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_3.setGeometry(QtCore.QRect(400, 420, 191, 51))
                self.label_9 = QtWidgets.QLabel(self.centralwidget)
                self.label_9.setGeometry(QtCore.QRect(270, 370, 331, 41))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_9.setFont(font)
                self.label_9.setText("")
                self.label_9.setObjectName("label_9")
                font = QtGui.QFont()
                font.setPointSize(11)
                self.pushButton_3.setFont(font)
                self.pushButton_3.setStyleSheet("QPushButton {\n"
        "    background-color: #555555;\n"
        "    color: white;\n"
        "    border-radius: 8px;\n"
        "    padding: 6px 12px;\n"
        "}\n"
        "\n"
        "QPushButton:hover {\n"
        "    background-color: #666666;\n"
        "}\n"
        "\n"
        "QPushButton:pressed {\n"
        "    background-color: #777777;\n"
        "}")
                self.pushButton_3.setObjectName("pushButton_3")
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

                #aksi
                self.pushButton.clicked.connect(self.CariUser)
                self.pushButton_2.clicked.connect(self.HapusUser)
                self.pushButton_3.clicked.connect(self.back)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label.setText(_translate("MainWindow", "Delete Data User"))
                self.label_3.setText(_translate("MainWindow", "Password"))
                self.label_4.setText(_translate("MainWindow", "Username"))
                self.label_5.setText(_translate("MainWindow", "Nama"))
                self.label_6.setText(_translate("MainWindow", "Role"))
                self.pushButton.setText(_translate("MainWindow", "Cari"))
                self.pushButton_2.setText(_translate("MainWindow", "Delete"))
                self.pushButton_3.setText(_translate("MainWindow", "Back"))

        def CariUser(self):
                username = self.lineEdit_2.text().strip()

                if username == "":
                        QMessageBox.warning(None, "Peringatan", "Username tidak boleh kosong!")
                        return

                data = Admin().select_by_username(username)

                if not data:
                        QMessageBox.warning(None, "Tidak Ditemukan", "User tidak ditemukan!")
                        self.label_7.setText("")
                        self.label_8.setText("")
                        self.label_9.setText("")
                        return

                if len(data) != 4:
                        QMessageBox.warning(None, "Error", "Format data user tidak valid!")
                        return

                nama, user, password, role = data

                # TAMPILKAN KE LABEL
                self.label_7.setText(nama)
                self.label_8.setText(password)
                self.label_9.setText(role)
        def HapusUser(self):
                username = self.lineEdit_2.text().strip()

                if username == "":
                        QMessageBox.warning(None, "Peringatan", "Isi username terlebih dahulu!")
                        return

                cek = Admin().select_by_username(username)
                if not cek:
                        QMessageBox.warning(None, "Error", "User tidak ditemukan!")
                        return

                Admin().delete_user(username)

                QMessageBox.information(None, "Berhasil", "User berhasil dihapus.")

                # CLEAR
                self.lineEdit_2.setText("")
                self.label_7.setText("")
                self.label_8.setText("")
                self.label_9.setText("")

        def back(self):
                from dashboard.dashboard_admin import Ui_MainWindow
                self.dashboard_window = QtWidgets.QMainWindow()
                self.dashboard = Ui_MainWindow()
                self.dashboard.setupUi(self.dashboard_window)
                self.dashboard_window.show()
                self.main_window.close()

if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
