# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_data_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from models.User import Admin, mycursor, mydb
from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                self.main_window = MainWindow 
                self.admin = Admin()    
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(800, 600)
                font = QtGui.QFont()
                font.setPointSize(11)
                MainWindow.setFont(font)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(250, 40, 291, 51))
                font = QtGui.QFont()
                font.setPointSize(18)
                font.setBold(True)
                font.setWeight(75)
                self.label.setFont(font)
                self.label.setObjectName("label")
                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(100, 290, 81, 31))
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(100, 190, 81, 41))
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(130, 240, 61, 31))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.label_5.setFont(font)
                self.label_5.setObjectName("label_5")
                self.label_6 = QtWidgets.QLabel(self.centralwidget)
                self.label_6.setGeometry(QtCore.QRect(130, 350, 55, 16))
                self.label_6.setObjectName("label_6")
                self.pushButton = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton.setGeometry(QtCore.QRect(490, 190, 81, 41))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.pushButton.setFont(font)
                self.pushButton.setStyleSheet("QPushButton {\n"
        "    background-color: #444444;\n"
        "    color: white;\n"
        "    border-radius: 8px;\n"
        "    padding: 6px 12px;\n"
        "}\n"
        "\n"
        "QPushButton:hover {\n"
        "    background-color: #333333;\n"
        "}\n"
        "\n"
        "QPushButton:pressed {\n"
        "    background-color: #222222;\n"
        "}")
                self.pushButton.setObjectName("pushButton")
                self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_2.setGeometry(QtCore.QRect(370, 410, 201, 51))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.pushButton_2.setFont(font)
                self.pushButton_2.setStyleSheet("QPushButton {\n"
        "    background-color: #444444;\n"
        "    color: white;\n"
        "    border-radius: 8px;\n"
        "    padding: 6px 12px;\n"
        "}\n"
        "\n"
        "QPushButton:hover {\n"
        "    background-color: #333333;\n"
        "}\n"
        "\n"
        "QPushButton:pressed {\n"
        "    background-color: #222222;\n"
        "}")
                self.pushButton_2.setObjectName("pushButton_2")
                self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEdit_2.setGeometry(QtCore.QRect(230, 190, 241, 41))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.lineEdit_2.setFont(font)
                self.lineEdit_2.setStyleSheet("QLineEdit {\n"
        "    background-color: #FFFFFF;\n"
        "    color: #333333;\n"
        "    border: 2px solid #555555;\n"
        "    border-radius: 6px;\n"
        "    padding: 4px;\n"
        "}\n"
        "\n"
        "QLineEdit:focus {\n"
        "    border: 2px solid #333333;\n"
        "}")
                self.lineEdit_2.setObjectName("lineEdit_2")
                self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEdit_3.setGeometry(QtCore.QRect(230, 240, 341, 41))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.lineEdit_3.setFont(font)
                self.lineEdit_3.setStyleSheet("QLineEdit {\n"
        "    background-color: #FFFFFF;\n"
        "    color: #333333;\n"
        "    border: 2px solid #555555;\n"
        "    border-radius: 6px;\n"
        "    padding: 4px;\n"
        "}\n"
        "\n"
        "QLineEdit:focus {\n"
        "    border: 2px solid #333333;\n"
        "}")
                self.lineEdit_3.setObjectName("lineEdit_3")
                self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEdit_4.setGeometry(QtCore.QRect(230, 290, 341, 41))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.lineEdit_4.setFont(font)
                self.lineEdit_4.setStyleSheet("QLineEdit {\n"
        "    background-color: #FFFFFF;\n"
        "    color: #333333;\n"
        "    border: 2px solid #555555;\n"
        "    border-radius: 6px;\n"
        "    padding: 4px;\n"
        "}\n"
        "\n"
        "QLineEdit:focus {\n"
        "    border: 2px solid #333333;\n"
        "}")
                self.lineEdit_4.setObjectName("lineEdit_4")
                self.comboBox_level = QtWidgets.QComboBox(self.centralwidget)
                self.comboBox_level.setGeometry(QtCore.QRect(230, 340, 341, 41))
                self.comboBox_level.setObjectName("comboBox_level")
                self.comboBox_level.addItem("Admin")
                self.comboBox_level.addItem("Supervisor")
                self.comboBox_level.addItem("Kasir")
                self.comboBox_level.setStyleSheet("""
        QComboBox {
        background-color: #FFFFFF;
        border: 2px solid #555555;
        border-radius: 6px;
        padding: 4px;
        color: #333333;
        font-size: 16px;
        }
        QComboBox::drop-down {
        border: none;
        }
        """)


                self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_3.setGeometry(QtCore.QRect(140, 410, 201, 51))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.pushButton_3.setFont(font)
                self.pushButton_3.setStyleSheet("QPushButton {\n"
        "    background-color: #444444;\n"
        "    color: white;\n"
        "    border-radius: 8px;\n"
        "    padding: 6px 12px;\n"
        "}\n"
        "\n"
        "QPushButton:hover {\n"
        "    background-color: #333333;\n"
        "}\n"
        "\n"
        "QPushButton:pressed {\n"
        "    background-color: #222222;\n"
        "}")
                self.pushButton_3.setObjectName("pushButton_3")
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

                #aksi
                self.pushButton.clicked.connect(self.CariUser)
                self.pushButton_3.clicked.connect(self.UpdateUser)
                self.pushButton_2.clicked.connect(self.back)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.label.setText(_translate("MainWindow", "Update Data User"))
                self.label_3.setText(_translate("MainWindow", "Password"))
                self.label_4.setText(_translate("MainWindow", "Username"))
                self.label_5.setText(_translate("MainWindow", "Nama"))
                self.label_6.setText(_translate("MainWindow", "Level"))
                self.pushButton.setText(_translate("MainWindow", "Cari"))
                self.pushButton_2.setText(_translate("MainWindow", "Back"))
                self.pushButton_3.setText(_translate("MainWindow", "Update"))

        def CariUser(self):
                # Ambil username dari input pencarian (lineEdit_2)
                username = self.lineEdit_2.text().strip()

                if username == "":
                        QMessageBox.warning(self.main_window, "Error", "Masukkan username yang ingin dicari!")
                        return

                # Query ke database
                data = self.admin.select_by_username(username)

                if not data:
                        QMessageBox.warning(self.main_window, "Error", "User tidak ditemukan!")
                        return

                # data = (nama, username, password, role)
                self.lineEdit_3.setText(str(data[0]))  # nama
                self.lineEdit_2.setText(str(data[1]))  # username
                self.lineEdit_4.setText(str(data[2]))  # password
                self.comboBox_level.setCurrentText(str(data[3]).capitalize())

                # Simpan untuk update nanti
                self.old_username = data[1]

        # ==========================================================
        # =================== FUNGSI UPDATE ========================
        # ==========================================================
        def UpdateUser(self):
                # Pastikan sudah cari user dulu
                if not hasattr(self, "old_username"):
                        QMessageBox.warning(self.main_window, "Error", "Cari user dulu sebelum update!")
                        return

                # Ambil input baru
                new_username = self.lineEdit_2.text().strip()
                new_nama = self.lineEdit_3.text().strip()
                new_password = self.lineEdit_4.text().strip()
                new_role = self.comboBox_level.currentText()

                # Validasi
                if not new_username or not new_nama or not new_password:
                        QMessageBox.warning(self.main_window, "Error", "Semua field harus diisi!")
                        return

                try:
                        self.admin.update_user(
                                nama=new_nama,
                                username=new_username,
                                password=new_password,
                                role=new_role,
                                old_username=self.old_username
                        )

                        QMessageBox.information(self.main_window, "Success", "Data user berhasil diperbarui!")

                        # Reset agar tidak update user yang sama dua kali
                        self.old_username = None

                except Exception as e:
                        QMessageBox.critical(self.main_window, "Error", f"Gagal update user: {e}")

        # ==========================================================
        # ==================== FUNGSI BACK =========================
        # ==========================================================
        def back(self):
                from dashboard.dashboard_admin import Ui_MainWindow
                self.dashboard_window = QtWidgets.QMainWindow()
                self.dashboard = Ui_MainWindow()
                self.dashboard.setupUi(self.dashboard_window)
                self.dashboard_window.show()
                self.main_window.close()
                
if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())